#!/bin/bash
theme='ndi305-50'
#theme='nmLDoO-of32-test'
#theme='nd35-35'
TYPE='T8a'
NAME='sample-inh-a'
lgnfile='1xu-'$theme'-s911'
#QUEUE1="adparallel"
#QUEUE2="adparallel"
#QUEUE2="gpu"
QUEUE1="s48"
QUEUE2="s48"
walltime=0:15:00
analysisTime=0:30:00

if [ ! -d "$NAME" ]; then
	mkdir $NAME
else
	cd $NAME
	rm -rf *
	cd ../
fi
cp conMat-$theme'_'$TYPE.mat conMat.mat
cp profile-$theme'_'$TYPE.out $NAME/profile.out
cp generateConMat-$theme'_'$TYPE.m gg-$theme'_'$TYPE $NAME
cp logNormalProfile-$theme'_'$TYPE.m $NAME/logNormalProfile.m
cp logNormalProfile-$theme'_'$TYPE.mat $NAME/logNormalProfile.mat
cp lgnmap.out-$lgnfile $NAME/lgnmap.out

cp bash_sim4x3 nextContrast.keys fitOnly4 sim4x1 sim4x2 sim4x3 ompaSep1 ompaSep2 ompaSep3 assa adg_INPUT conMat.mat $NAME 
cd $NAME
date

jobList=""
i=1
for gtheta in 1-4 5-8 9-12
do
    if [ "$gtheta" == "1-4" ]; then
        QUEUE="$QUEUE1"
    else
        QUEUE="$QUEUE2"
    fi
    contrast=1
    while [ $contrast -le 4 ]; do
        jobID=`qsub -q $QUEUE -l walltime=$walltime -l mem=20GB -l nodes=1:ppn=4 sim4x$i`
        vim -s nextContrast.keys sim4x$i
        echo $jobID = $contrast
        jobList="$jobList:$jobID"
        ((contrast++))
    done
    echo $gtheta
    echo $i
    ((i++))
done
echo all contrasts done
qsub -l walltime=$analysisTime -W depend=afterany$jobList -q $QUEUE2 fitOnly4
