#!/bin/bash
set -e
theme='nd305-40s1-2'       # LGN setup name
walltime=01:00:00
analysisTime=0:45:00
TYPE='8'                # type of cortical connection
######## Please find the following variable description in pA.slurm ########
NAME='s12-8-iv1'             # folder name for this simulation
PRESET=$theme            # lgn presets file
FORMAT='png'               # figure format for saving
individOnly="false"        # plot individual neurons’ figures only
statsOnly="true"           # plot populational figures only
rt=10                     #   run time of simulation (exclude the warm-up time), some plots will give wrong firing rate if not set correctly as in adg_INPUT 
fit="false"                 # fit the tuning curves for width.
npool=1                   # number of cpus used to fit tuning curves, set to 1 if fit=="false"
thres=0.25                 # a gauge of firing rate threshold for active, non-active, non-active neurons were not included in some of the plots
NTHETA="12"                # number of angles in simulation
CONTRASTS="4"              # number of constrast used in simulation
ld="false"                 #   default to false, if already acquired sim data as ".mat" file, set to true
MeanNorm="true"

if [ ! -d "$NAME" ]; then
	mkdir $NAME
else
	cd $NAME
	rm -rf *
	cd ../
fi
fname=$theme'_'$TYPE
mkdir $NAME/sim_package_backup
cp conMat-$fname.mat conMat.mat
cp profile-$fname.out $NAME/profile.out
cp logNormalProfile-$theme'_'$TYPE.mat $NAME/logNormalProfile.mat
cp lgnmap.out-$theme $NAME/lgnmap.out

cp sbatch_sim4x3 nextContrast.keys plotAll4.slurm sim4x1.slurm sim4x2.slurm sim4x3.slurm ompaSep1 ompaSep2 ompaSep3 assa adg_INPUT conMat.mat $NAME 
cd $NAME
date

jobList=""
i=1
for gtheta in 1-4 5-8 9-12
do
    contrast=1
    while [ $contrast -le 4 ]; do
        jobID=`sbatch -p serial --time=$walltime -J sim --mem=20GB --nodes=1 --cpus-per-task=4 sim4x$i.slurm`
        vim -s nextContrast.keys sim4x$i.slurm
        echo $jobID = $contrast
        jobList="$jobList:${jobID:20}"
        ((contrast++))
    done
    echo $gtheta
    echo $i
    ((i++))
done
echo all contrasts done
export NAME
export PRESET
export FORMAT
export individOnly
export statsOnly
export ld
export fit
export rt
export npool
export thres
export fit
export NTHETA
export CONTRASTS
export MeanNorm

sbatch --export=ALL -p serial --time=$analysisTime --cpus-per-task=$npool --dependency=afterok$jobList plotAll4.slurm
