#!/bin/bash

walltime=0:40:00
mem=30G
load=false          # load new src files to run and delete everything old
fdr='test'              # target simulation folder
theme='ndc305-40'       # lgn mapping name, pls set the p.suffix in gMap2.m to the same value 
TYPE='6'                # additional type name for RFcoeff, OP difference and cortical connection
conmat=conMat-$theme'_'$TYPE  # name for connection matrix
coMa='coMa-60x60-'$theme'_'$TYPE   # name for RF pearson coefficient matrix
EPSPprofile='logNormal'     # type of distribution for EPSP
edist='coGauss'             # E-E connection strength type
eiSpecific='true'          # E<-I connection specificity over orientation preference
threads=12          # number of threads used in parpool for RFcoef_O_beta.m
antiphase='false'       # antiphase in terms of on-off subregion, so that RF coefficient is bigger if on-off cross match between two neurons
reciprocal=0.0          # constraint on percentage of reciprocal connections 0.0 for no constraint
drawInh='true'      # if draw inhibitory example; 
ld='false'          # don't re-generate lgn to v1 map, outdated
ldRF='false'          # don't re-generate lgn to V1 RF, outdated

tw=0.5             # weight of contributions from orientation preference and RFcoeff to connection preference, dependent on "reverse", examine in RFcoeff_O_beta.m
temper=30           # std of the guassian noise added to temper with the preset orientation of recruiting ellipses
wC=1               # 1-percentage of random orientation std for explicit complex cell
temperGrad='true'           # give a gradient to tempered orientation on normalized distance between on-off subregion
ntheta=12           # number of angles simulated
ex=10               #  # of example plots
p2s=40.0            # estimated converting scale from connection strength to resulting PSP
mu=0.45             # average EPSP in mV
ieSpecific='false'  # keep it false, its coMat is not implemented in RFcoeff_O_beta.m (set I<-E specific connection over oriention preference)
sig=1.16           # standard deviation for a lognormal distribution
mu0=0.45           # with a mean value of mu0
nsig=3             # cutoff EPSP histogram at # of std 
nbins=30            # number of bins for EPSP distribution
spread='false'      # unrelated test variable, assign EPSP value to E->E connections by subregion normalized distance, ignore.
lowestRatio=0.00    # related to variable "spread", ignore if complex cell is not an issue.

setupFdr='Setup_'$theme'_'$TYPE
if [ ! -d "$setupFdr" ]; then
    mkdir $setupFdr
fi
## pre copy
if [ "$load" == true ]; then
    cd $setupFdr
    rm -rf *
    cd ../
    cp *.m gg.slurm  $setupFdr/
fi
cp sbatch_gg $setupFdr/

cd $setupFdr

export fdr
export TYPE
export theme
export conmat
export coMa
export EPSPprofile
export edist
export eiSpecific
export antiphase
export reciprocal
export drawInh
export ld
export ldRF
export threads
export tw
export temper
export ntheta
export ex
export p2s
export mu
export ieSpecific
export sig
export mu0
export nsig
export nbins
export spread
export lowestRatio
export temperGrad 
export wC
sbatch --export=ALL --mem=$mem --time=$walltime gg.slurm
